/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.uidsl.ide.contentassist.antlr.internal.InternalUiDslParser;
import org.xtext.example.uidsl.services.UiDslGrammarAccess;

public class UiDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(UiDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, UiDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getUiModelAccess().getGroup(), "rule__UiModel__Group__0");
			builder.put(grammarAccess.getUiModelFileAccess().getUiModelsAssignment(), "rule__UiModelFile__UiModelsAssignment");
			builder.put(grammarAccess.getUiModelAccess().getNameAssignment_1(), "rule__UiModel__NameAssignment_1");
			builder.put(grammarAccess.getUiModelAccess().getModelAssignment_3(), "rule__UiModel__ModelAssignment_3");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private UiDslGrammarAccess grammarAccess;

	@Override
	protected InternalUiDslParser createParser() {
		InternalUiDslParser result = new InternalUiDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public UiDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UiDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
