/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.modeldsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ModelDslStandaloneSetup extends ModelDslStandaloneSetupGenerated {

	public static void doSetup() {
		new ModelDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
