/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.ide;


/**
 * Use this class to register ide components.
 */
public class UiDslIdeModule extends AbstractUiDslIdeModule {
}
