/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class UiDslUiModule extends AbstractUiDslUiModule {

	public UiDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
