/*
 * generated by Xtext 2.22.0
 */
grammar InternalUiDsl;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.example.uidsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.example.uidsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.example.uidsl.services.UiDslGrammarAccess;

}

@parser::members {

 	private UiDslGrammarAccess grammarAccess;

    public InternalUiDslParser(TokenStream input, UiDslGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "UiModelFile";
   	}

   	@Override
   	protected UiDslGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleUiModelFile
entryRuleUiModelFile returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUiModelFileRule()); }
	iv_ruleUiModelFile=ruleUiModelFile
	{ $current=$iv_ruleUiModelFile.current; }
	EOF;

// Rule UiModelFile
ruleUiModelFile returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getUiModelFileAccess().getUiModelsUiModelParserRuleCall_0());
			}
			lv_uiModels_0_0=ruleUiModel
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getUiModelFileRule());
				}
				add(
					$current,
					"uiModels",
					lv_uiModels_0_0,
					"org.xtext.example.uidsl.UiDsl.UiModel");
				afterParserOrEnumRuleCall();
			}
		)
	)*
;

// Entry rule entryRuleUiModel
entryRuleUiModel returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getUiModelRule()); }
	iv_ruleUiModel=ruleUiModel
	{ $current=$iv_ruleUiModel.current; }
	EOF;

// Rule UiModel
ruleUiModel returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='ui'
		{
			newLeafNode(otherlv_0, grammarAccess.getUiModelAccess().getUiKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getUiModelAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getUiModelRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='for'
		{
			newLeafNode(otherlv_2, grammarAccess.getUiModelAccess().getForKeyword_2());
		}
		(
			(
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getUiModelRule());
					}
				}
				otherlv_3=RULE_ID
				{
					newLeafNode(otherlv_3, grammarAccess.getUiModelAccess().getModelModelCrossReference_3_0());
				}
			)
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
