/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.modeldsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.xtext.example.modeldsl.modelDsl.Model;
import org.xtext.example.modeldsl.modelDsl.ModelDslPackage;
import org.xtext.example.modeldsl.modelDsl.ModelFile;
import org.xtext.example.modeldsl.services.ModelDslGrammarAccess;

@SuppressWarnings("all")
public class ModelDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ModelDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ModelDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ModelDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case ModelDslPackage.MODEL_FILE:
				sequence_ModelFile(context, (ModelFile) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     ModelFile returns ModelFile
	 *
	 * Constraint:
	 *     models+=Model+
	 */
	protected void sequence_ModelFile(ISerializationContext context, ModelFile semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     (abstract?='abstract'? name=ID)
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
