/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.uidsl.ui.internal.UidslActivator;

public class UiDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return UidslActivator.getInstance().getInjector("org.xtext.example.uidsl.UiDsl");
	}

}
