/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public class UiDslScopeProvider extends DelegatingScopeProvider {
}
