/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.uidsl.parser.antlr.internal.InternalUiDslParser;
import org.xtext.example.uidsl.services.UiDslGrammarAccess;

public class UiDslParser extends AbstractAntlrParser {

	@Inject
	private UiDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalUiDslParser createParser(XtextTokenStream stream) {
		return new InternalUiDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "UiModelFile";
	}

	public UiDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(UiDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
