/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.modeldsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public class ModelDslScopeProvider extends DelegatingScopeProvider {
}
