/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.uiDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.uidsl.uiDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class UiDslFactoryImpl extends EFactoryImpl implements UiDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static UiDslFactory init()
  {
    try
    {
      UiDslFactory theUiDslFactory = (UiDslFactory)EPackage.Registry.INSTANCE.getEFactory(UiDslPackage.eNS_URI);
      if (theUiDslFactory != null)
      {
        return theUiDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new UiDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UiDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case UiDslPackage.UI_MODEL_FILE: return createUiModelFile();
      case UiDslPackage.UI_MODEL: return createUiModel();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UiModelFile createUiModelFile()
  {
    UiModelFileImpl uiModelFile = new UiModelFileImpl();
    return uiModelFile;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UiModel createUiModel()
  {
    UiModelImpl uiModel = new UiModelImpl();
    return uiModel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public UiDslPackage getUiDslPackage()
  {
    return (UiDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static UiDslPackage getPackage()
  {
    return UiDslPackage.eINSTANCE;
  }

} //UiDslFactoryImpl
