/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.uiDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.uidsl.uiDsl.UiDslFactory
 * @model kind="package"
 * @generated
 */
public interface UiDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "uiDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/uidsl/UiDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "uiDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UiDslPackage eINSTANCE = org.xtext.example.uidsl.uiDsl.impl.UiDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.uidsl.uiDsl.impl.UiModelFileImpl <em>Ui Model File</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uidsl.uiDsl.impl.UiModelFileImpl
   * @see org.xtext.example.uidsl.uiDsl.impl.UiDslPackageImpl#getUiModelFile()
   * @generated
   */
  int UI_MODEL_FILE = 0;

  /**
   * The feature id for the '<em><b>Ui Models</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL_FILE__UI_MODELS = 0;

  /**
   * The number of structural features of the '<em>Ui Model File</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL_FILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.uidsl.uiDsl.impl.UiModelImpl <em>Ui Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.uidsl.uiDsl.impl.UiModelImpl
   * @see org.xtext.example.uidsl.uiDsl.impl.UiDslPackageImpl#getUiModel()
   * @generated
   */
  int UI_MODEL = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL__MODEL = 1;

  /**
   * The number of structural features of the '<em>Ui Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UI_MODEL_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link org.xtext.example.uidsl.uiDsl.UiModelFile <em>Ui Model File</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ui Model File</em>'.
   * @see org.xtext.example.uidsl.uiDsl.UiModelFile
   * @generated
   */
  EClass getUiModelFile();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.uidsl.uiDsl.UiModelFile#getUiModels <em>Ui Models</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Ui Models</em>'.
   * @see org.xtext.example.uidsl.uiDsl.UiModelFile#getUiModels()
   * @see #getUiModelFile()
   * @generated
   */
  EReference getUiModelFile_UiModels();

  /**
   * Returns the meta object for class '{@link org.xtext.example.uidsl.uiDsl.UiModel <em>Ui Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ui Model</em>'.
   * @see org.xtext.example.uidsl.uiDsl.UiModel
   * @generated
   */
  EClass getUiModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.uidsl.uiDsl.UiModel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.uidsl.uiDsl.UiModel#getName()
   * @see #getUiModel()
   * @generated
   */
  EAttribute getUiModel_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.uidsl.uiDsl.UiModel#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Model</em>'.
   * @see org.xtext.example.uidsl.uiDsl.UiModel#getModel()
   * @see #getUiModel()
   * @generated
   */
  EReference getUiModel_Model();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  UiDslFactory getUiDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.uidsl.uiDsl.impl.UiModelFileImpl <em>Ui Model File</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uidsl.uiDsl.impl.UiModelFileImpl
     * @see org.xtext.example.uidsl.uiDsl.impl.UiDslPackageImpl#getUiModelFile()
     * @generated
     */
    EClass UI_MODEL_FILE = eINSTANCE.getUiModelFile();

    /**
     * The meta object literal for the '<em><b>Ui Models</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UI_MODEL_FILE__UI_MODELS = eINSTANCE.getUiModelFile_UiModels();

    /**
     * The meta object literal for the '{@link org.xtext.example.uidsl.uiDsl.impl.UiModelImpl <em>Ui Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.uidsl.uiDsl.impl.UiModelImpl
     * @see org.xtext.example.uidsl.uiDsl.impl.UiDslPackageImpl#getUiModel()
     * @generated
     */
    EClass UI_MODEL = eINSTANCE.getUiModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UI_MODEL__NAME = eINSTANCE.getUiModel_Name();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UI_MODEL__MODEL = eINSTANCE.getUiModel_Model();

  }

} //UiDslPackage
