/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.uiDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.uidsl.uiDsl.UiDslPackage
 * @generated
 */
public interface UiDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  UiDslFactory eINSTANCE = org.xtext.example.uidsl.uiDsl.impl.UiDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Ui Model File</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ui Model File</em>'.
   * @generated
   */
  UiModelFile createUiModelFile();

  /**
   * Returns a new object of class '<em>Ui Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ui Model</em>'.
   * @generated
   */
  UiModel createUiModel();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  UiDslPackage getUiDslPackage();

} //UiDslFactory
