/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.uiDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ui Model File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.uidsl.uiDsl.UiModelFile#getUiModels <em>Ui Models</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.uidsl.uiDsl.UiDslPackage#getUiModelFile()
 * @model
 * @generated
 */
public interface UiModelFile extends EObject
{
  /**
   * Returns the value of the '<em><b>Ui Models</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.uidsl.uiDsl.UiModel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ui Models</em>' containment reference list.
   * @see org.xtext.example.uidsl.uiDsl.UiDslPackage#getUiModelFile_UiModels()
   * @model containment="true"
   * @generated
   */
  EList<UiModel> getUiModels();

} // UiModelFile
