/**
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl.uiDsl;

import org.eclipse.emf.ecore.EObject;

import org.xtext.example.modeldsl.modelDsl.Model;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ui Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.uidsl.uiDsl.UiModel#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.uidsl.uiDsl.UiModel#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.uidsl.uiDsl.UiDslPackage#getUiModel()
 * @model
 * @generated
 */
public interface UiModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.uidsl.uiDsl.UiDslPackage#getUiModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.uidsl.uiDsl.UiModel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference.
   * @see #setModel(Model)
   * @see org.xtext.example.uidsl.uiDsl.UiDslPackage#getUiModel_Model()
   * @model
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link org.xtext.example.uidsl.uiDsl.UiModel#getModel <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

} // UiModel
