/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.modeldsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ModelDslUiModule extends AbstractModelDslUiModule {

	public ModelDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
