/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.uidsl;

import org.xtext.example.modeldsl.ModelDslStandaloneSetup;

import com.google.inject.Injector;

/**
 * Initialization support for running Xtext languages without Equinox extension
 * registry.
 */
public class UiDslStandaloneSetup extends UiDslStandaloneSetupGenerated {

	public static void doSetup() {
		new UiDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
	
	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		ModelDslStandaloneSetup.doSetup();
		return super.createInjectorAndDoEMFRegistration();
	}
}
