/*
 * generated by Xtext 2.22.0
 */
package org.xtext.example.modeldsl.ide;


/**
 * Use this class to register ide components.
 */
public class ModelDslIdeModule extends AbstractModelDslIdeModule {
}
